unmannedfactory/lumino/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from . import views

app_name = "lumino"

router = DefaultRouter()
router.register(r'products', views.ProductsViewSet)
router.register(r'orders', views.OrdersViewSet)
router.register(r'ordersdetail', views.OrdersDetailViewSet)
router.register(r'employees', views.EmployeesViewSet)
router.register(r'employeestask', views.EmployeestaskViewSet)

urlpatterns = [
    path('', views.index, name="index"),
    path('carrobots/', views.carrobots, name="carrobots"),
    path('members/', views.members, name="members"),
    path('products/', views.products, name="products"),
    path('orders/', views.orders, name="orders"),
    path('login/', views.login, name="login"),
    path('api/v1/group/', views.getjson, name="getjson"),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    path('api/v1/products',views.getProduct,name="getProduct"),
    path('api/v1/products/update',views.productUpdate,name="productUpdate"),
]

unmannedfactory/unmannedfactory/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from lumino import views

router = DefaultRouter()
router.register(r'drivelesscar', views.DrivelesscarViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lumino.urls')),
    url(r'^api/', include(router.urls))
]

unmannedfactory/templates/__empty.html
{% extends 'base.html' %}{% block content %} 


<!-- Write your code here -->


{% endblock %}

unmannedfactory/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lumino - Widgets</title>
	<link href="{% static 'lumino/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'lumino/css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'lumino/css/datepicker3.css' %}" rel="stylesheet">
	<link href="{% static 'lumino/css/styles.css' %}" rel="stylesheet">
	<!--Custom Font-->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
</head>
<body>

	{% include 'nav.html' %}
	
	{% include 'sidebar.html' %}
		
	{% block content %} {% endblock %}


	<script src="{% static 'lumino/js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'lumino/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'lumino/js/chart.min.js' %}"></script>
	<script src="{% static 'lumino/js/chart-data.js' %}"></script>
	<script src="{% static 'lumino/js/easypiechart.js' %}"></script>
	<script src="{% static 'lumino/js/easypiechart-data.js' %}"></script>
	<script src="{% static 'lumino/js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'lumino/js/custom.js' %}"></script>
</body>
</html>

unmannedfactory/templates/nav.html
{% load static %}
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span></button>
            <a class="navbar-brand" href="#"><span>Lumino</span>Admin</a>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <em class="fa fa-envelope"></em><span class="label label-danger">15</span>
                </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box"><a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="http://placehold.it/40/30a5ff/fff">
                                </a>
                                <div class="message-body"><small class="pull-right">3 mins ago</small>
                                    <a href="#"><strong>John Doe</strong> commented on <strong>your photo</strong>.</a>
                                <br /><small class="text-muted">1:24 pm - 25/03/2015</small></div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="dropdown-messages-box"><a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="http://placehold.it/40/30a5ff/fff">
                                </a>
                                <div class="message-body"><small class="pull-right">1 hour ago</small>
                                    <a href="#">New message from <strong>Jane Doe</strong>.</a>
                                <br /><small class="text-muted">12:27 pm - 25/03/2015</small></div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="all-button"><a href="#">
                                <em class="fa fa-inbox"></em> <strong>All Messages</strong>
                            </a></div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <em class="fa fa-bell"></em><span class="label label-info">5</span>
                </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li><a href="#">
                            <div><em class="fa fa-envelope"></em> 1 New Message
                                <span class="pull-right text-muted small">3 mins ago</span></div>
                        </a></li>
                        <li class="divider"></li>
                        <li><a href="#">
                            <div><em class="fa fa-heart"></em> 12 New Likes
                                <span class="pull-right text-muted small">4 mins ago</span></div>
                        </a></li>
                        <li class="divider"></li>
                        <li><a href="#">
                            <div><em class="fa fa-user"></em> 5 New Followers
                                <span class="pull-right text-muted small">4 mins ago</span></div>
                        </a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.container-fluid -->
</nav>

unmannedfactory/templates/sidebar.html
{% load static %}
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <div class="profile-sidebar">
        <div class="profile-userpic">
            <img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
        </div>
        <div class="profile-usertitle">
            <div class="profile-usertitle-name">Username</div>
            <div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form>
    <ul class="nav menu">
        <li class="active"><a href="{% url 'lumino:index' %}"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a></li>
        <li><a href="{% url 'lumino:products' %}"><em class="fa fa-calendar">&nbsp;</em> Products</a></li>
        <li><a href="{% url 'lumino:members' %}"><em class="fa fa-bar-chart">&nbsp;</em> Members</a></li>
        <li><a href="{% url 'lumino:carrobots' %}"><em class="fa fa-toggle-off">&nbsp;</em> CarRobots</a></li>
        <li><a href="{% url 'lumino:orders' %}"><em class="fa fa-clone">&nbsp;</em> Orders </a></li>
        <li class="parent "><a data-toggle="collapse" href="#sub-item-1">
            <em class="fa fa-navicon">&nbsp;</em> Multilevel <span data-toggle="collapse" href="#sub-item-1" class="icon pull-right"><em class="fa fa-plus"></em></span>
            </a>
            <ul class="children collapse" id="sub-item-1">
                <li><a class="" href="#">
                    <span class="fa fa-arrow-right">&nbsp;</span> Sub Item 1
                </a></li>
                <li><a class="" href="#">
                    <span class="fa fa-arrow-right">&nbsp;</span> Sub Item 2
                </a></li>
                <li><a class="" href="#">
                    <span class="fa fa-arrow-right">&nbsp;</span> Sub Item 3
                </a></li>
            </ul>
        </li>
        <li><a href="{% url 'lumino:login' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
    </ul>
</div><!--/.sidebar-->